---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

verifier:
  name: inspec

provisioner:
  name: dokken
  attributes:
    apt:
      confd:
        install_recommends: false

platforms:
  - name: ubuntu16
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: ubuntu18
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq

  - name: debian8
    driver:
      image: debian:8.9
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: centos6
    driver:
      image: centos:6.10
      pid_one_command: /sbin/init
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which curl

  - name: centos7
    driver:
      image: centos:7.6.1810
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: fedora28
    driver:
      image: fedora:28
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: amazon
    driver:
      image: amazonlinux:2018.03.0.20190212
      pid_one_command: /sbin/init
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which

  - name: amazon2
    driver:
      image: amazonlinux:2.0.20190228
      pid_one_command: /usr/lib/systemd/systemd
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts

suites:
  - name: chef13
    driver:
      chef_version: 13.12.14
    verifier:
      inspec_tests:
        - test/smoke/v6
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef14
    driver:
      chef_version: 14.11.21
    verifier:
      inspec_tests:
        - test/smoke/v6
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef14runit
    driver:
      chef_version: 14.11.21
    verifier:
      inspec_tests:
        - test/smoke/v6runit
    run_list:
      - recipe[filebeat_test::defaultv6runit]

  - name: chef14preview
    driver:
      chef_version: 14.11.21
    run_list:
      - recipe[filebeat_test::defaultv6preview]
