sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't run bundle install
install: echo "skip bundle install"

branches:
  only:
    - master
    - /^(?i:travis).*$/

services: docker

env:
  matrix:
    - INSTANCE=chef14-centos6
    - INSTANCE=chef14-centos7
    - INSTANCE=chef14-fedora28
    - INSTANCE=chef14-ubuntu16
    - INSTANCE=chef14-ubuntu18
    - INSTANCE=chef14-debian8
    - INSTANCE=chef14-debian9
    - INSTANCE=chef14-amazon
    - INSTANCE=chef14-amazon2

script:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
  - cat .kitchen/logs/kitchen.log

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version


matrix:
  allow_failures:
    - env: INSTANCE=chef14v6-amazon2

  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
